import africanViolet from '../assets/products/african-violet.png';
import aluminiumPlant from '../assets/products/aluminium-plant.png';
import angelWingBegonia from '../assets/products/angel-wing-begonia.png';
import barbertonDaisy from '../assets/products/barberton-daisy.png';
import beachSpiderLily from '../assets/products/beach-spider-lily.png';
import birdsNestFern from "../assets/products/birds-nest-fern.png";
import blushingBromeliad from '../assets/products/blushing-bromeliad.png';
import broadleafLadyPalm from '../assets/products/broadleaf-lady-palm.png';
import chineseEvergreen from '../assets/products/chinese-evergreen.png';

export const plantsDb = [
    {
        name: 'Barberton Daisy',
        id: '1',
        img: barbertonDaisy,
        price: '$119.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Angel Wing Begonia',
        id: '2',
        img: angelWingBegonia,
        price: '$169.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'African Violet',
        id: '3',
        img: africanViolet,
        price: '$229.00',
        discountPrice: '$199.00',
        sale: true,
        discount: '13% OFF',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Beach Spider Lily',
        id: '4',
        img: beachSpiderLily,
        price: '$129.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Blushing Bromeliad',
        id: '5',
        img: blushingBromeliad,
        price: '$139.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Aluminum Plant',
        id: '6',
        img: aluminiumPlant,
        price: '$179.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: "Bird's Nest Fern",
        id: '7',
        img: birdsNestFern,
        price: '$99.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Broadleaf Lady Palm',
        id: '8',
        img: broadleafLadyPalm,
        price: '$59.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },
    {
        name: 'Chinese Evergreen',
        id: '9',
        img: chineseEvergreen,
        price: '$39.00',
        discountPrice: '',
        sale: false,
        discount: '',
        date: new Date(),
        liked: false,
        cart: false,
    },

]